
name: Run Tests Doxa

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
   runs-on: ubuntu-latest

   steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
       node-version: 16.18
       
    - run: npm ci
    - run: npm run build --if-present
    
#   - name: Run tests
#      run: npm test

